k9s:
  cluster: qa08-central-ve
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - default
  view:
    active: cronjob
  featureGates:
    nodeShell: false
  proxy: null
