k9s:
  cluster: walnut-use2-p00
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: jobs
  featureGates:
    nodeShell: false
  proxy: null
