k9s:
  cluster: arn:aws:eks:us-east-2:748964902751:cluster/wichita
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - default
  view:
    active: nodes
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
