k9s:
  cluster: hospital-use2-p00
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: pods
  featureGates:
    nodeShell: false
  proxy: null
