k9s:
  cluster: sanity
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - cattle-monitoring-system
      - default
  view:
    active: pods
  featureGates:
    nodeShell: false
  proxy: null
