k9s:
  cluster: qa01
  namespace:
    active: cattle-monitoring-system
    lockFavorites: false
    favorites:
      - cattle-monitoring-system
      - all
      - cattle-logging-system
      - kube-system
      - secrets-operator
      - default
  view:
    active: v1/nodes
  featureGates:
    nodeShell: false
  proxy: null
