k9s:
  cluster: arn:aws:eks:us-west-2:748964902751:cluster/molex-amea
  namespace:
    active: default
    lockFavorites: false
    favorites:
    - default
  view:
    active: nodes
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
