k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: dev-euw2-mgmt
  currentCluster: dev-euw2-mgmt
  clusters:
    arn:aws:eks:us-east-1:300852543289:cluster/qa-scale2:
      namespace:
        active: cattle-system
        lockFavorites: false
        favorites:
        - all
        - cattle-system
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    demo:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - elisity-monitoring
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    dev-euw2-mgmt:
      namespace:
        active: arc-runner-system
        lockFavorites: false
        favorites:
        - scale-dev01
        - siem
        - argocd
        - arc-runner-system
        - cnpg-system
        - argowf
        - cattle-system
        - cattle-monitoring-system
        - all
      view:
        active: context
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    dev01:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: secret
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    dev02:
      namespace:
        active: cattle-monitoring-system
        lockFavorites: false
        favorites:
        - cattle-monitoring-system
        - default
      view:
        active: secrets
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    eks06:
      namespace:
        active: elisity-monitoring
        lockFavorites: false
        favorites:
        - elisity-monitoring
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    eks07:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - secrets-operator
        - default
      view:
        active: clustersecretstores.external-secrets.io
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    hln-wey:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: statefulset
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    local-ghgtff5878:
      namespace:
        active: argocd
        lockFavorites: false
        favorites:
        - argocd
        - default
      view:
        active: nodes
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    mmc-d528922t9c:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: nodes
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    mskcc:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: deployments
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    pfe:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    qa-nightly:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - elisity-monitoring
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    qa-test-release:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: configmap
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    qa05-iam:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - elisity-monitoring
        - default
      view:
        active: deployment
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    qa06:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - elisity-monitoring
        - default
      view:
        active: secrets
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    qa06-edisco:
      namespace:
        active: elisity-monitoring
        lockFavorites: false
        favorites:
        - elisity-monitoring
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
    qa07-ve:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/wy/233vk4696qg9gyl40yzbl7d00000gn/T/k9s-screens-mkania
