k9s:
  cluster: gsk-nasa01
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: pods
  featureGates:
    nodeShell: false
  proxy: null
