k9s:
  cluster: corning
  namespace:
    active: default
    lockFavorites: false
    favorites:
    - default
  view:
    active: pods
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
